### PR TITLE
Pin rake to < 11 for Ruby 1.8.7

### PR DESCRIPTION
**Pull request by domcleal**
Should fix the error seen at https://github.com/theforeman/puppet-puppet/pull/356#issuecomment-194586010 and https://travis-ci.org/theforeman/puppet-puppet/jobs/114805305.

### CODE REVIEW

**Comment by ekohl** [comment]
:+1:

**Comment by mmoll** [comment]
merged, thanks @domcleal!

**Comment by domcleal** [comment]
modulesync branches are now up and should be running through Travis.  They contain this and https://github.com/theforeman/foreman-installer-modulesync/commit/c6837c6d804646ed74e3efd9f34a5aa5c284d447.

**Comment by domcleal** [comment]
All modulesyncs merged into master.

**Pull request merged**
