### PR TITLE
Rspec helper functions

### PR DESCRIPTION
**Pull request by pall-valmundsson**
As per https://github.com/theforeman/puppet-puppet/pull/318

### CODE REVIEW

**Comment by ekohl** [comment]
I liked your changes to travis.yml as well because there's no need to test ruby 1.8.7 + EL7 or debian jessie. Mind including those as well?

**Comment by pall-valmundsson** [comment]
I can do that, but keep in mind that the filters won't work unless this boilerplate is in all spec files:
```
  on_supported_os.each do |os, facts|
    next if only_test_os() and not only_test_os.include?(os)
    next if exclude_test_os() and exclude_test_os.include?(os)
```

**Comment by ekohl** [comment]
I know that, but that will allow us to easily implement it in other modules as well (puppet-foreman could really use it for example).

**Comment by pall-valmundsson** [comment]
Ok. That's in here as well.

**Comment by mmoll** [comment]
:+1:

**Comment by domcleal** [comment]
:+1:

**Comment by ekohl** [comment]
Thanks!

**Comment by domcleal** [comment]
I've submitted a PR (https://github.com/rodjek/rspec-puppet/pull/329) to rspec-puppet to limit the number of cached catalogs, which if accepted should mean we can remove the monkey patch at a later date.  I also fixed a bug causing the cache to have no/little effect on Puppet 2 and 3, so we should see a performance increase there too.

**Pull request merged**
