### PR TITLE
Fixes #29189 - pin beaker <= 4.22.0

### PR DESCRIPTION
**Pull request by wbclark**

### CODE REVIEW

**Comment by mmoll** [comment]
Does Puppet Labs know of the problem?

**Comment by wbclark** [comment]
> Does Puppet Labs know of the problem?

Yes, the fix is https://github.com/puppetlabs/beaker/pull/1642

**Comment by wbclark** [comment]
This should be strictly less than, or <= 4.21.0.... will fix it

**Comment by mmoll** [comment]
A fixed version has been released, so either we leave it as-is (no special handling) or require `>= 4.22.1`

**Comment by ekohl** [comment]
I think no special handling is needed for this.

**Pull request closed without merging**
