### PR TITLE
[WIP] Allow deploying modules to the forge

### PR DESCRIPTION
**Pull request by ekohl**
Travis can deploy a module to the puppet forge when a tag is pushed.  This makes it easier to release a module.

Untested right now. I'm thinking about checking if a tag is GPG signed but wondering how much that actually adds.

### CODE REVIEW

**Comment by zjhuntin** [comment]
Is there a way to test this locally? It seems logical to me, but I'd be happy to give it a go.

**Comment by ekohl** [comment]
You can run `bundle install && bundle exec msync update --noop` to update the modules without pushing. That way you can see the rendered changes. Note that modules need a secret in their `.sync.yml` so the `if` statement is true.

I intend to transfer https://github.com/ekohl/puppet-foreman_simple_user to the foreman org and publish it on the forge. That should be my testcase of automatically pushing a tag and checking what Travis does. I'm not aware of an easier method.

**Comment by ekohl** [comment]
I've opened for a public discussion: https://community.theforeman.org/t/releasing-puppet-modules-via-travis/10387

**Comment by ekohl** [comment]
We're likely going to be moving away from Travis so I'm going to close this.

**Pull request closed without merging**
