### PR TITLE
Add ERB file extensions to resolve modulesync 0.8.0 deprecation

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by ekohl** [comment]
Do we need to have every file with a ```.erb``` extension? I believe the docker nodesets and a few other files have no templating at all.

**Comment by domcleal** [comment]
Yes, irrespective of ERB content or not.

**Comment by mmoll** [comment]
Merged, thanks @domcleal!

Side note: I did a noop-sync and the newly generated .travis.ymls do look incorrect...

**Comment by mmoll** [comment]
turns out, everything is OK 👍

**Pull request merged**
