### PR TITLE
manage puppet-foreman_network and puppet-foreman_scap_client

### PR DESCRIPTION
**Pull request by roidelapluie**

### CODE REVIEW

**Comment by ekohl** [comment]
Currently these aren't really managed by the installer team, but maybe we should. @domcleal / @mmoll?

**Comment by mmoll** [comment]
We could do that, although I'm not fond of the existence of puppet-foreman_network and have no idea of openscap.

**Comment by roidelapluie** [comment]
well their travis.ci etc are behind our standards

**Comment by domcleal** [comment]
I don't know anything about them, have no wish to maintain them personally.

**Comment by ares** [comment]
FWIW puppet-foreman_scap_client - this one is used by foreman_openscap to configure client side, it's tiny and I think there would be interest of catching up with Foreman standards

**Pull request closed without merging**
