### PR TITLE
Add new puppet-lint checks for Puppet 4 compatibility

### PR DESCRIPTION
**Pull request by domcleal**
From http://www.camptocamp.com/actualite/getting-code-ready-puppet-4/

---

I'll open up per-module PRs to show where we have failures and then we can work to fix them.

- https://github.com/theforeman/puppet-concat_native/pull/7 (merged)
- https://github.com/theforeman/puppet-dhcp/pull/39 (merged)
- https://github.com/theforeman/puppet-dns/pull/27 (merged)
- https://github.com/theforeman/puppet-foreman/pull/293 (merged)
- https://github.com/theforeman/puppet-foreman_proxy/pull/153 (merged)
- https://github.com/theforeman/puppet-git/pull/12 (merged)
- https://github.com/theforeman/puppet-puppet/pull/242 (merged)
- https://github.com/theforeman/puppet-tftp/pull/28 (merged)

### CODE REVIEW

**Comment by domcleal** [comment]
FYI, @ekohl and @mmoll you have collab rights on my repos if you feel like pushing fixes to the existing branches :)

**Comment by domcleal** [comment]
All merged :)

**Comment by ekohl** [comment]
Does it need a rebase or shall we just merge it?

**Comment by domcleal** [comment]
Rebased.

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
