### PR TITLE
Tune the operatingsystem platforms where we run Ruby 1.8.7 tests

### PR DESCRIPTION
**Pull request by roidelapluie**

### CODE REVIEW

**Comment by domcleal** [comment]
Test run still going, linked at https://github.com/theforeman/puppet-puppet/issues/330#issuecomment-160587890.

Looks good to me, if it works!

**Comment by roidelapluie** [comment]
@Dominic It is OK

**Comment by domcleal** [comment]
That's good, only one hour.

**Comment by roidelapluie** [comment]
And I opened #23 for Puppet 2.7.0

**Comment by mmoll** [comment]
:+1: looking good to me.

**Comment by domcleal** [comment]
Merged, thanks @roidelapluie!

**Pull request merged**
