### PR TITLE
Rspec puppet facts

### PR DESCRIPTION
**Pull request by mcanevet**

### CODE REVIEW

**Comment by domcleal** [comment]
Thanks, running tests on all modules now.

**Comment by ekohl** [comment]
http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/ suggests adding  ```cache: bundler``` to cache gems. This could help a lot with the speed as well.

**Comment by domcleal** [comment]
Good idea, I've added that to my tests.  (Which are taking ages..)

**Comment by domcleal** [comment]
Bundler caching introduces a whole load of problems with the Puppet module testing gems right now due to it storing gems in vendor/bundle/ by default, so we'll have to skip that.  (It appears we could set BUNDLE_PATH to something, maybe /tmp, but my patience has run out today.)

https://github.com/puppetlabs/puppetlabs_spec_helper/pull/86 links to the various problems I hit.  Hopefully in a few months it'll be workable.

**Comment by domcleal** [comment]
@mcanevet our 1.8.7 tests failed, https://github.com/mcanevet/rspec-puppet-facts/pull/4 should fix it

**Comment by mcanevet** [comment]
@domcleal . @raphink did that as a workaround for our modules:  https://github.com/camptocamp/modulesync_configs/blob/master/moduleroot/Rakefile#L14

**Comment by domcleal** [comment]
I think that only works as you're using puppet-lint < 1.1.0 too... 1.1.0 changed how to define the rake task, and introduced a new bug.

**Comment by domcleal** [comment]
Merged, thanks @mcanevet!

**Pull request merged**
