### PR TITLE
test all OSes

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by ekohl** [comment]
With parallel tests does, it still make sense to split it up so much?

**Comment by mmoll** [comment]
When I look at the current Ruby 2.1 test runtimes, it's looking nicely balanced, but if we agree on reducing the Ruby 2.1 matrix, we could always use the same OS set.

**Comment by ekohl** [comment]
Does splitting in major and minor distros still make sense?

**Comment by mmoll** [comment]
The longest testrun is taking 19 minutes, so it's quite safe.

**Comment by ekohl** [comment]
I also noticed that Debian 9 isn't in the metadata for many modules. Is this a preparation to add it?

**Comment by ekohl** [comment]
Oh, and should we still exclude Scientific Linux from the tests? I'm confident it's 99.99% the same as CentOS.

**Comment by mmoll** [comment]
> I also noticed that Debian 9 isn't in the metadata for many modules. Is this a preparation to add it?

exactly.

> Oh, and should we still exclude Scientific Linux from the tests? I'm confident it's 99.99% the same as CentOS.

I don't have a preference on that one. I think at least for the moment the slowdown is bearable.

**Comment by ekohl** [comment]
> I don't have a preference on that one. I think at least for the moment the slowdown is bearable.

Fair enough.

**Comment by mmoll** [comment]
anything else needed to get this in? :)

**Comment by ekohl** [comment]
Nope, thanks :)

**Pull request merged**
