### PR TITLE
Allow Failure for Puppet 2.7

### PR DESCRIPTION
**Pull request by roidelapluie**

### CODE REVIEW

**Comment by domcleal** [comment]
We could probably just remove it completely if there's no further posts to my -users/-dev threads soon.

**Comment by roidelapluie** [comment]
Yeah, the goal is anyway green builds again :)

**Comment by mmoll** [comment]
:+1: for deleting 2.7 when there are no further replies.

**Comment by mmoll** [comment]
As there were zero replies on the lists, I propose to rebase this PR onto current master and amend it to remove Puppet 2.7.

**Comment by domcleal** [comment]
Yep, agreed.

**Comment by roidelapluie** [comment]
Here you have

**Comment by domcleal** [comment]
Thanks, looks good.  OK with you too @ekohl?

**Comment by ekohl** [comment]
:+1: it's time to say goodbye to 2.7. Question is whether we will drop it per 1.10 or 1.11. I'm leaning to 1.11.

**Comment by roidelapluie** [comment]
@ekohl if you read the mail it says 1.11

**Comment by domcleal** [comment]
1.11 I'd say, since 1.10's branched and working fine to the best of my knowledge.  The breaking concat change hasn't been released, so the `< 1.3.0` version we're pinned to in foreman-installer's 1.10-stable branch ought to be fine.

**Comment by domcleal** [comment]
Thanks @roidelapluie, merged.

@mmoll is working on a Ruby 2.2 update for modulesync, so once that's in too then I'll run msync.

**Comment by roidelapluie** [comment]
@domcleal https://github.com/theforeman/theforeman.org/issues/490

**Pull request merged**
