### PR TITLE
Update puppet_metadata dependency to ~> 4.0

### PR DESCRIPTION
**Pull request by archanaserver**
https://github.com/theforeman/foreman-infra/issues/2087

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
While you're at it, I think you need to update voxpupuli-acceptance to `~> 3.0` because I'm not sure 2.x is compatible.

Could you also submit the pull requests for at least one module to see if it works?

**Review by ekohl — APPROVED** [review]

**Comment by archanaserver** [comment]
@ekohl if it is working now, do we need any other changes to get it in?

**Comment by ekohl** [comment]
@archanaserver it looks good, please submit PRs for all the managed modules.

**Comment by archanaserver** [comment]
@ekohl I've submit all the PRs for all the managed modules, tracking it here: https://github.com/theforeman/foreman-infra/issues/2087#issuecomment-2197151432

**Pull request merged**
