### PR TITLE
Drop Puppet 3 support

### PR DESCRIPTION
**Pull request by ekohl**
Not to be merged until we have made all the releases and branches.

### CODE REVIEW

**Comment by ekohl** [comment]
@mmoll given everything has been released, think it's time to pull the trigger?

**Comment by mmoll** [comment]
I'll create x.x-stable branches in the puppet modules repo first

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Comment by domcleal** [comment]
modulesync branches pushed.

**Pull request merged**
